### ISSUE TITLE
Fix SwagerGen so non-nullable properties are required in OpenApi schema 

### ISSUE THREAD

**Issue by bookuha** [HokkuSengoku/IVQ.WebApi#2]
Currently, non-[Required] properties are considered optional (in OpenApi spec), even though they will always be provided a value in scope of .NET. I want to override this behavior (make non-nullable properties required in OpenApi) so OpenApi generators will give desired output.

Useful links:
[A possible solution overriding SwaggerGen and using C# required keyword](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2555)
[Some info on nullability in ASP.NET](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2036#issuecomment-1293304351)
[Microsoft documentation on [Required] behavior](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-7.0#non-nullable-reference-types-and-required-attribute)

**Comment by piskov** [comment]
@bookuha, @HokkuSengoku hey guys! Does this PR take into account default values?

E. g.
```
public string Prop { get; init; } = "default value";
```

It’s non-nullable, yet it shoudn’t be required as it has a default value.

See how [ASP validation is working](https://github.com/dotnet/aspnetcore/pull/38801) as a result of this [issue](https://github.com/dotnet/aspnetcore/issues/18403)
